### PR TITLE
Update tier_three.json

### PR DESCRIPTION
**Pull request by AnOrinaryCabbage**
Added diamond and netherite tools (including swords), enchanted golden apple, sharpness enchant for swords (disclaimer: all code additions are all guessed based on your code so if there's any problem, you can edit it as you like) (and you can add tnt and flint n steel if you want)

### CODE REVIEW

**Comment by hainam333** [comment]
also, i forgot to add armors in the file so you can add them in all tiers

**Review by hampfh — CHANGES_REQUESTED** [review]
Hi, for me to accept these changes you must first make sure that they are indeed working. Test the code and get back to me again when you're certain that it works. Thanks for contributing

**Review by AnOrinaryCabbage — COMMENTED** [review]
That would be ok (how to merge your change though?)

**Comment by hainam333** [comment]
sadly, it didn't work...

**Comment by Hampfh** [comment]
Hi again, when you make commits to your branch `patch-2` this pull request will be updated. That's how you perform changes

**Pull request closed without merging**
